### ISSUE TITLE
quick_server not defined

### ISSUE THREAD

**Issue by ilmw** [nyuvis/explanation_explorer#1]
When I ran the mushroom example, after obtaining .csv and .json files, I started the server and got error: ReferenceError: quick_server is not defined. (It initially displayed no error but didn't work; the error showed up after surrounding "var work = quick_server.Worker();" near line 130 in index.html with a try-catch block) Would you please kindly explain what went wrong here?

**Comment by JosuaKrause** [comment]
it looks like the quick-server library had some breaking changes in the mean time. version 0.4.12 should be working correctly (`pip install --upgrade --force-reinstall quick-server==0.4.12`)
let me know if that solves your issue -- I will update the codebase accordingly if it does

**Comment by ilmw** [comment]
Thanks a lot for the prompt response!

Shawn

________________________________

**Comment by ilmw** [comment]
Yes it's working. Thanks!

**Comment by JosuaKrause** [comment]
Awesome! 4933b43afd19b3f0a7fdaecb2d02e58eaadb565e prevents this issue happening in the future and makes fresh installs work.
